// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ibop.Api.Data;

#nullable disable

namespace ibop.Api.Migrations
{
    [DbContext(typeof(IbopDbContext))]
    [Migration("20260108012335_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("680645ce-8113-4c18-80f3-280b360660e8"),
                            CreatedAt = new DateTime(2026, 1, 8, 1, 23, 34, 353, DateTimeKind.Utc).AddTicks(1364),
                            Email = "admin@ibop.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEDpdvmeQzPk5OLaDSSu50a1kq3D7wvZuPZrwibwh894aF3uEv8T/P0gd8A63j5yBZg==",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("252d9f88-7d28-4b90-80fe-6839baaa2722"),
                            CreatedAt = new DateTime(2026, 1, 8, 1, 23, 34, 438, DateTimeKind.Utc).AddTicks(4356),
                            Email = "manager@ibop.com",
                            FirstName = "Manager",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEC5Su+fB1vyE4ar9Iy42dFH/tjQQ80cbbyJmQdqWMrRYv0hrC8XkylI+I/AC9VEUvw==",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("010efa23-1c78-4fdb-b40f-a1dde436ec70"),
                            CreatedAt = new DateTime(2026, 1, 8, 1, 23, 34, 509, DateTimeKind.Utc).AddTicks(9526),
                            Email = "staff@ibop.com",
                            FirstName = "Staff",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEFnyf5FrHyc99YDTItZa1Wm/JQ/vsKNXh/O5btB5nvzE/t+9JtzmuGLEjIKLTiNLbg==",
                            Role = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
